import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Providers from "./Providers";
import Navbar from "./components/Navbar";
import SearchBox from "./components/SearchBox";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "IMDb Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="dark:bg-gray-700 dark:text-gray-200 bg-white text-gray-700 min-h-screen transition-colors duration-300 select-none">
        <Providers>
          {/* Header */}
          <Header/> 

          {/* Navbar */}
          <Navbar/>

          {/* Searchbox */}
          <SearchBox/>
          
          {children}
        </Providers>
      </body>
    </html>
  );
}
